language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'

install:
  - yarn

script:
  - yarn lint && yarn test && yarn report-coverage

cache:
  yarn: true
  directories:
    - node_modules
