language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'

install:
  - yarn

script:
  - yarn lint && yarn test && yarn report-coverage

cache:
  yarn: true
  directories:
    - node_modules
